root = "path/to/root/for/repos"
[logger]
log_level = "Warn" # Debug | Info | Warn | Error

# version that should be set to the package on specific branch
[git]
target_branch = "dev-510-batch"
source_branch = "dev-59"

[aws]
role_script_path="path/to/sso.zsh"
role="role_name_here"

[repos]
node_workers = [
  'conform5-bpo-api',
]

python_workers = [
  'conform5-lambda-batch-vr-python-custom-code',
]



